package com.gartenplan.pro.domain.model

import com.gartenplan.pro.core.constants.*

/**
 * Domain model for Plant
 */
data class Plant(
    val id: String,
    val nameDE: String,
    val nameEN: String,
    val latinName: String? = null,
    val category: PlantCategory,
    val sowIndoorStart: Int? = null,
    val sowIndoorEnd: Int? = null,
    val sowOutdoorStart: Int? = null,
    val sowOutdoorEnd: Int? = null,
    val harvestStart: Int,
    val harvestEnd: Int,
    val daysToGermination: Int? = null,
    val daysToHarvest: Int? = null,
    val spacingInRowCm: Int,
    val spacingBetweenRowsCm: Int,
    val plantDepthCm: Int? = null,
    val nutrientDemand: NutrientLevel,
    val waterDemand: WaterLevel,
    val sunRequirement: SunLevel,
    val description: String? = null,
    val careTips: String? = null,
    val diseases: List<String> = emptyList(),
    val pests: List<String> = emptyList(),
    val imageUrl: String? = null,
    val isFavorite: Boolean = false,
    val isProOnly: Boolean = false
) {
    fun getName(isGerman: Boolean = true): String = if (isGerman) nameDE else nameEN
    
    fun canSowIndoorInMonth(month: Int): Boolean {
        return sowIndoorStart != null && sowIndoorEnd != null &&
               month >= sowIndoorStart && month <= sowIndoorEnd
    }
    
    fun canSowOutdoorInMonth(month: Int): Boolean {
        return sowOutdoorStart != null && sowOutdoorEnd != null &&
               month >= sowOutdoorStart && month <= sowOutdoorEnd
    }
    
    fun canHarvestInMonth(month: Int): Boolean {
        return month >= harvestStart && month <= harvestEnd
    }
    
    fun getAreaPerPlantCm2(): Int = spacingInRowCm * spacingBetweenRowsCm
}

/**
 * Domain model for Companion relationship
 */
data class CompanionInfo(
    val plant: Plant,
    val relationship: CompanionType,
    val reasonDE: String? = null,
    val reasonEN: String? = null
) {
    fun getReason(isGerman: Boolean = true): String? = if (isGerman) reasonDE else reasonEN
}

/**
 * Domain model for Garden
 */
data class Garden(
    val id: String,
    val name: String,
    val widthCm: Int,
    val heightCm: Int,
    val climateZone: String = "7a",
    val postalCode: String? = null,
    val createdAt: Long,
    val updatedAt: Long,
    val imageUri: String? = null,
    val notes: String? = null,
    val beds: List<Bed> = emptyList()
) {
    fun getAreaM2(): Float = (widthCm * heightCm) / 10000f
    fun getWidthM(): Float = widthCm / 100f
    fun getHeightM(): Float = heightCm / 100f
}

/**
 * Domain model for Bed
 */
data class Bed(
    val id: String,
    val gardenId: String,
    val name: String,
    val positionX: Int,
    val positionY: Int,
    val widthCm: Int,
    val heightCm: Int,
    val shape: BedShape = BedShape.RECTANGLE,
    val secondaryWidthCm: Int? = null,
    val secondaryHeightCm: Int? = null,
    val raisedHeightCm: Int = 0,
    val isPath: Boolean = false,
    val colorHex: String = "#8D6E63",
    val soilType: String? = null,
    val notes: String? = null,
    val placements: List<PlantPlacement> = emptyList()
) {
    fun getAreaM2(): Float = (widthCm * heightCm) / 10000f
    fun isRaisedBed(): Boolean = raisedHeightCm > 0
}

/**
 * Domain model for PlantPlacement
 */
data class PlantPlacement(
    val id: String,
    val bedId: String,
    val plant: Plant,
    val positionX: Int,
    val positionY: Int,
    val widthCm: Int,
    val heightCm: Int,
    val quantity: Int = 1,
    val year: Int,
    val cultureType: CultureType,
    val sowDate: Long? = null,
    val transplantDate: Long? = null,
    val harvestDate: Long? = null,
    val status: PlantingStatus,
    val notes: String? = null
)

enum class CultureType { PRE, MAIN, POST }
enum class PlantingStatus { PLANNED, SOWN, TRANSPLANTED, GROWING, HARVESTING, HARVESTED, FAILED }

/**
 * Domain model for Task
 */
data class Task(
    val id: String,
    val gardenId: String,
    val bedId: String? = null,
    val plantId: String? = null,
    val title: String,
    val description: String? = null,
    val taskType: TaskType,
    val dueDate: Long,
    val reminderTime: Long? = null,
    val isCompleted: Boolean = false,
    val completedAt: Long? = null,
    val isAutoGenerated: Boolean = false,
    val priority: Int = 2,
    val isRecurring: Boolean = false,
    val recurringDays: Int? = null
)

/**
 * Domain model for Compost
 */
data class Compost(
    val id: String,
    val name: String,
    val startedAt: Long,
    val expectedReadyAt: Long? = null,
    val status: CompostStatus,
    val notes: String? = null,
    val entries: List<CompostEntry> = emptyList(),
    val greenRatio: Float = 0f,
    val brownRatio: Float = 0f
)

enum class CompostStatus { ACTIVE, RESTING, READY, USED }

data class CompostEntry(
    val id: String,
    val compostId: String,
    val materialType: CompostMaterialType,
    val customMaterialName: String? = null,
    val isGreen: Boolean,
    val amountLiters: Float? = null,
    val addedAt: Long,
    val notes: String? = null
)
