package com.gartenplan.pro.domain.repository

import com.gartenplan.pro.core.constants.CompanionType
import com.gartenplan.pro.core.constants.PlantCategory
import com.gartenplan.pro.domain.model.*
import kotlinx.coroutines.flow.Flow

/**
 * Repository interface for Plant operations
 */
interface PlantRepository {
    fun getAllPlants(): Flow<List<Plant>>
    fun getPlantsByCategory(category: PlantCategory): Flow<List<Plant>>
    fun searchPlants(query: String): Flow<List<Plant>>
    fun getFavoritePlants(): Flow<List<Plant>>
    fun getPlantsBySowingMonth(month: Int): Flow<List<Plant>>
    fun getPlantsByHarvestMonth(month: Int): Flow<List<Plant>>
    
    suspend fun getPlantById(id: String): Plant?
    suspend fun updateFavoriteStatus(plantId: String, isFavorite: Boolean)
    suspend fun getPlantCount(): Int
    
    // Companion plants
    fun getCompanionsForPlant(plantId: String): Flow<List<CompanionInfo>>
    fun getGoodCompanions(plantId: String): Flow<List<CompanionInfo>>
    fun getBadCompanions(plantId: String): Flow<List<CompanionInfo>>
    suspend fun getCompanionRelationship(plantId1: String, plantId2: String): CompanionType?
}

/**
 * Repository interface for Garden operations
 */
interface GardenRepository {
    fun getAllGardens(): Flow<List<Garden>>
    fun observeGardenById(id: String): Flow<Garden?>
    fun observeGardenCount(): Flow<Int>
    fun getBedsByGarden(gardenId: String): Flow<List<Bed>>
    fun getPlacementsByBed(bedId: String): Flow<List<PlantPlacement>>
    fun getPlacementsByBedAndYear(bedId: String, year: Int): Flow<List<PlantPlacement>>
    
    suspend fun getGardenById(id: String): Garden?
    suspend fun getGardenCount(): Int
    suspend fun getBedById(id: String): Bed?
    suspend fun createGarden(garden: Garden): String
    suspend fun updateGarden(garden: Garden)
    suspend fun deleteGarden(gardenId: String)
    
    suspend fun createBed(bed: Bed): String
    suspend fun updateBed(bed: Bed)
    suspend fun deleteBed(bedId: String)
    
    suspend fun createPlacement(placement: PlantPlacement): String
    suspend fun updatePlacement(placement: PlantPlacement)
    suspend fun deletePlacement(placementId: String)
    
    // Crop rotation
    suspend fun getPreviousYearPlacements(bedId: String, currentYear: Int): List<PlantPlacement>
}

/**
 * Repository interface for Task operations
 */
interface TaskRepository {
    fun getTasksByGarden(gardenId: String): Flow<List<Task>>
    fun getTasksForDateRange(gardenId: String, startDate: Long, endDate: Long): Flow<List<Task>>
    fun getTasksForDay(gardenId: String, dayStart: Long, dayEnd: Long): Flow<List<Task>>
    fun getPendingTasks(gardenId: String, today: Long): Flow<List<Task>>
    fun getOverdueTasks(gardenId: String, today: Long): Flow<List<Task>>
    fun getUpcomingTasks(gardenId: String, today: Long, endDate: Long): Flow<List<Task>>
    fun getCompletedTasks(gardenId: String): Flow<List<Task>>
    fun countPendingTasks(gardenId: String): Flow<Int>
    fun countTasksForToday(gardenId: String, dayStart: Long, dayEnd: Long): Flow<Int>
    
    suspend fun getTaskById(id: String): Task?
    suspend fun createTask(task: Task): String
    suspend fun updateTask(task: Task)
    suspend fun deleteTask(taskId: String)
    suspend fun markTaskCompleted(taskId: String)
    suspend fun markTaskNotCompleted(taskId: String)
    suspend fun deleteAutoGeneratedTasks(gardenId: String)
}

/**
 * Repository interface for Compost operations
 */
interface CompostRepository {
    fun getAllComposts(): Flow<List<Compost>>
    fun getActiveComposts(): Flow<List<Compost>>
    fun observeCompostById(id: String): Flow<Compost?>
    fun getEntriesByCompost(compostId: String): Flow<List<CompostEntry>>
    
    suspend fun getCompostById(id: String): Compost?
    suspend fun createCompost(compost: Compost): String
    suspend fun updateCompost(compost: Compost)
    suspend fun deleteCompost(compostId: String)
    suspend fun updateCompostStatus(compostId: String, status: CompostStatus)
    
    suspend fun addEntry(entry: CompostEntry): String
    suspend fun deleteEntry(entryId: String)
    suspend fun getGreenBrownRatio(compostId: String): Pair<Float, Float>
}
