package com.gartenplan.pro.data.local.dao

import androidx.room.*
import com.gartenplan.pro.core.constants.TaskType
import com.gartenplan.pro.data.local.entity.TaskEntity
import kotlinx.coroutines.flow.Flow

/**
 * Data Access Object for Task operations
 */
@Dao
interface TaskDao {
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertTask(task: TaskEntity)
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertTasks(tasks: List<TaskEntity>)
    
    @Update
    suspend fun updateTask(task: TaskEntity)
    
    @Delete
    suspend fun deleteTask(task: TaskEntity)
    
    @Query("DELETE FROM tasks WHERE id = :taskId")
    suspend fun deleteTaskById(taskId: String)
    
    @Query("DELETE FROM tasks WHERE gardenId = :gardenId AND isAutoGenerated = 1")
    suspend fun deleteAutoGeneratedTasks(gardenId: String)
    
    // Get all tasks for a garden
    @Query("SELECT * FROM tasks WHERE gardenId = :gardenId ORDER BY dueDate ASC")
    fun getTasksByGarden(gardenId: String): Flow<List<TaskEntity>>
    
    // Get tasks for a specific date range
    @Query("""
        SELECT * FROM tasks 
        WHERE gardenId = :gardenId 
        AND dueDate >= :startDate AND dueDate <= :endDate
        ORDER BY dueDate ASC, priority DESC
    """)
    fun getTasksForDateRange(gardenId: String, startDate: Long, endDate: Long): Flow<List<TaskEntity>>
    
    // Get tasks for a specific day
    @Query("""
        SELECT * FROM tasks 
        WHERE gardenId = :gardenId 
        AND dueDate >= :dayStart AND dueDate < :dayEnd
        ORDER BY priority DESC, dueDate ASC
    """)
    fun getTasksForDay(gardenId: String, dayStart: Long, dayEnd: Long): Flow<List<TaskEntity>>
    
    // Get pending tasks (not completed, due date <= today)
    @Query("""
        SELECT * FROM tasks 
        WHERE gardenId = :gardenId 
        AND isCompleted = 0 
        AND dueDate <= :today
        ORDER BY dueDate ASC, priority DESC
    """)
    fun getPendingTasks(gardenId: String, today: Long): Flow<List<TaskEntity>>
    
    // Get overdue tasks
    @Query("""
        SELECT * FROM tasks 
        WHERE gardenId = :gardenId 
        AND isCompleted = 0 
        AND dueDate < :today
        ORDER BY dueDate ASC
    """)
    fun getOverdueTasks(gardenId: String, today: Long): Flow<List<TaskEntity>>
    
    // Get upcoming tasks (next X days)
    @Query("""
        SELECT * FROM tasks 
        WHERE gardenId = :gardenId 
        AND isCompleted = 0 
        AND dueDate >= :today AND dueDate <= :endDate
        ORDER BY dueDate ASC, priority DESC
    """)
    fun getUpcomingTasks(gardenId: String, today: Long, endDate: Long): Flow<List<TaskEntity>>
    
    // Get completed tasks
    @Query("""
        SELECT * FROM tasks 
        WHERE gardenId = :gardenId 
        AND isCompleted = 1
        ORDER BY completedAt DESC
    """)
    fun getCompletedTasks(gardenId: String): Flow<List<TaskEntity>>
    
    // Get tasks by type
    @Query("""
        SELECT * FROM tasks 
        WHERE gardenId = :gardenId 
        AND taskType = :taskType
        ORDER BY dueDate ASC
    """)
    fun getTasksByType(gardenId: String, taskType: TaskType): Flow<List<TaskEntity>>
    
    // Get tasks for a specific bed
    @Query("""
        SELECT * FROM tasks 
        WHERE bedId = :bedId
        ORDER BY dueDate ASC
    """)
    fun getTasksByBed(bedId: String): Flow<List<TaskEntity>>
    
    // Get tasks for a specific plant
    @Query("""
        SELECT * FROM tasks 
        WHERE plantId = :plantId
        ORDER BY dueDate ASC
    """)
    fun getTasksByPlant(plantId: String): Flow<List<TaskEntity>>
    
    // Mark task as completed
    @Query("""
        UPDATE tasks 
        SET isCompleted = 1, completedAt = :completedAt, updatedAt = :completedAt 
        WHERE id = :taskId
    """)
    suspend fun markTaskCompleted(taskId: String, completedAt: Long = System.currentTimeMillis())
    
    // Mark task as not completed
    @Query("""
        UPDATE tasks 
        SET isCompleted = 0, completedAt = NULL, updatedAt = :updatedAt 
        WHERE id = :taskId
    """)
    suspend fun markTaskNotCompleted(taskId: String, updatedAt: Long = System.currentTimeMillis())
    
    // Get task by ID
    @Query("SELECT * FROM tasks WHERE id = :id")
    suspend fun getTaskById(id: String): TaskEntity?
    
    // Count pending tasks
    @Query("""
        SELECT COUNT(*) FROM tasks 
        WHERE gardenId = :gardenId 
        AND isCompleted = 0
    """)
    fun countPendingTasks(gardenId: String): Flow<Int>
    
    // Count tasks for today
    @Query("""
        SELECT COUNT(*) FROM tasks 
        WHERE gardenId = :gardenId 
        AND isCompleted = 0
        AND dueDate >= :dayStart AND dueDate < :dayEnd
    """)
    fun countTasksForToday(gardenId: String, dayStart: Long, dayEnd: Long): Flow<Int>
}
