package com.gartenplan.pro.data.repository

import com.gartenplan.pro.data.local.dao.TaskDao
import com.gartenplan.pro.data.mapper.toDomain
import com.gartenplan.pro.data.mapper.toEntity
import com.gartenplan.pro.data.mapper.toTaskDomainList
import com.gartenplan.pro.domain.model.Task
import com.gartenplan.pro.domain.repository.TaskRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class TaskRepositoryImpl @Inject constructor(
    private val taskDao: TaskDao
) : TaskRepository {

    override fun getTasksByGarden(gardenId: String): Flow<List<Task>> {
        return taskDao.getTasksByGarden(gardenId).map { it.toTaskDomainList() }
    }

    override fun getTasksForDateRange(gardenId: String, startDate: Long, endDate: Long): Flow<List<Task>> {
        return taskDao.getTasksForDateRange(gardenId, startDate, endDate).map { it.toTaskDomainList() }
    }

    override fun getTasksForDay(gardenId: String, dayStart: Long, dayEnd: Long): Flow<List<Task>> {
        return taskDao.getTasksForDay(gardenId, dayStart, dayEnd).map { it.toTaskDomainList() }
    }

    override fun getPendingTasks(gardenId: String, today: Long): Flow<List<Task>> {
        return taskDao.getPendingTasks(gardenId, today).map { it.toTaskDomainList() }
    }

    override fun getOverdueTasks(gardenId: String, today: Long): Flow<List<Task>> {
        return taskDao.getOverdueTasks(gardenId, today).map { it.toTaskDomainList() }
    }

    override fun getUpcomingTasks(gardenId: String, today: Long, endDate: Long): Flow<List<Task>> {
        return taskDao.getUpcomingTasks(gardenId, today, endDate).map { it.toTaskDomainList() }
    }

    override fun getCompletedTasks(gardenId: String): Flow<List<Task>> {
        return taskDao.getCompletedTasks(gardenId).map { it.toTaskDomainList() }
    }

    override fun countPendingTasks(gardenId: String): Flow<Int> {
        return taskDao.countPendingTasks(gardenId)
    }

    override fun countTasksForToday(gardenId: String, dayStart: Long, dayEnd: Long): Flow<Int> {
        return taskDao.countTasksForToday(gardenId, dayStart, dayEnd)
    }

    override suspend fun getTaskById(id: String): Task? {
        return taskDao.getTaskById(id)?.toDomain()
    }

    override suspend fun createTask(task: Task): String {
        taskDao.insertTask(task.toEntity())
        return task.id
    }

    override suspend fun updateTask(task: Task) {
        taskDao.updateTask(task.toEntity())
    }

    override suspend fun deleteTask(taskId: String) {
        taskDao.deleteTaskById(taskId)
    }

    override suspend fun markTaskCompleted(taskId: String) {
        taskDao.markTaskCompleted(taskId)
    }

    override suspend fun markTaskNotCompleted(taskId: String) {
        taskDao.markTaskNotCompleted(taskId)
    }

    override suspend fun deleteAutoGeneratedTasks(gardenId: String) {
        taskDao.deleteAutoGeneratedTasks(gardenId)
    }
}
