package com.gartenplan.pro.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import com.gartenplan.pro.core.constants.TaskType

/**
 * Entity representing a garden task
 */
@Entity(
    tableName = "tasks",
    foreignKeys = [
        ForeignKey(
            entity = GardenEntity::class,
            parentColumns = ["id"],
            childColumns = ["gardenId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = BedEntity::class,
            parentColumns = ["id"],
            childColumns = ["bedId"],
            onDelete = ForeignKey.SET_NULL
        ),
        ForeignKey(
            entity = PlantEntity::class,
            parentColumns = ["id"],
            childColumns = ["plantId"],
            onDelete = ForeignKey.SET_NULL
        )
    ],
    indices = [
        Index(value = ["gardenId"]),
        Index(value = ["bedId"]),
        Index(value = ["plantId"]),
        Index(value = ["dueDate"]),
        Index(value = ["isCompleted"])
    ]
)
data class TaskEntity(
    @PrimaryKey
    val id: String,
    
    val gardenId: String,
    val bedId: String? = null,
    val plantId: String? = null,
    
    val title: String,
    val description: String? = null,
    
    val taskType: TaskType,
    
    // Due date (timestamp)
    val dueDate: Long,
    
    // Reminder (timestamp, null = no reminder)
    val reminderTime: Long? = null,
    
    // Completion
    val isCompleted: Boolean = false,
    val completedAt: Long? = null,
    
    // Auto-generated task (from planting calendar)
    val isAutoGenerated: Boolean = false,
    
    // Priority (1 = low, 2 = normal, 3 = high)
    val priority: Int = 2,
    
    // Recurring task
    val isRecurring: Boolean = false,
    val recurringDays: Int? = null,     // Repeat every X days
    
    // Metadata
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)
